# Generated by Django 3.0.5 on 2020-04-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_teste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(default='Geral', max_length=50),
        ),
    ]
