# Generated by Django 3.0.5 on 2020-04-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('nPaginas', models.IntegerField()),
                ('autor', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='dado',
            name='livros',
            field=models.ManyToManyField(to='site_teste.Livro'),
        ),
    ]
